name: Django CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

env:
  SECRET_KEY: 'django-insecure-development-key-for-ci-cd-testing'
  DEBUG: 'True'
  POSTGRES_DB: 'mydatabase'
  POSTGRES_USER: 'myuser'
  POSTGRES_PASSWORD: 'mypassword'
  POSTGRES_HOST: 'localhost'
  POSTGRES_PORT: '5432'

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_DB: mydatabase
          POSTGRES_USER: myuser
          POSTGRES_PASSWORD: mypassword
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    
    - name: Run migrations
      run: |
        python manage.py migrate
    
    - name: Run tests
      run: |
        python manage.py test

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build Docker images
      run: |
        docker build -t myproject-web -f Dockerfile .
        docker build -t myproject-nginx -f nginx/Dockerfile ./nginx
    
    - name: Log in to Docker Hub
      if: success()
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Push Docker images
      if: success()
      run: |
        docker tag myproject-web ${{ secrets.DOCKERHUB_USERNAME }}/django-app:latest
        docker tag myproject-nginx ${{ secrets.DOCKERHUB_USERNAME }}/django-nginx:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/django-app:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/django-nginx:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Deploy to production
      run: |
        echo "Deployment would happen here"
        echo "Add your deployment commands like:"
        echo "ssh user@server 'cd /app && docker-compose pull && docker-compose up -d'"
