name: Django CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_DB: mydatabase
          POSTGRES_USER: myuser
          POSTGRES_PASSWORD: mypassword
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        cd django_app
        pip install -r requirements.txt
    
    - name: Run migrations
      run: |
        cd django_app
        python manage.py migrate
      env:
        POSTGRES_DB: mydatabase
        POSTGRES_USER: myuser
        POSTGRES_PASSWORD: mypassword
        POSTGRES_HOST: localhost
        POSTGRES_PORT: 5432
        DEBUG: True
    
    - name: Run tests
      run: |
        cd django_app
        python manage.py test
      env:
        POSTGRES_DB: mydatabase
        POSTGRES_USER: myuser
        POSTGRES_PASSWORD: mypassword
        POSTGRES_HOST: localhost
        POSTGRES_PORT: 5432
        DEBUG: True

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Build Docker images
      run: |
        docker-compose -f docker-compose.prod.yml build
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Push Docker images
      run: |
        docker tag django-docker-project_web ${{ secrets.DOCKERHUB_USERNAME }}/django-app:latest
        docker tag django-docker-project_nginx ${{ secrets.DOCKERHUB_USERNAME }}/django-nginx:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/django-app:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/django-nginx:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Deploy to production
      run: |
        echo "Deploying to production server..."
        # Add your deployment commands here
        # For example, using SSH to connect to your server
        # and pull the new images